branch-defaults:
  62-Deploy-to-EB:
    environment: develop3
    group_suffix: null
global:
  application_name: vkr-orlova
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
