version: '3.3'

services:
    db:
        image: mysql:8.0.23
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
